# Generated by Django 4.2.1 on 2023-05-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonLog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='人员ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
                ('pic', models.ImageField(max_length=255, upload_to='images/person_img')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='用户名'),
        ),
    ]
