# Generated by Django 4.2.1 on 2023-05-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonLog', '0002_person_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(max_length=255, null=True, upload_to='images/person_img'),
        ),
    ]
